### ISSUE TITLE
HTML5 : Error message when you try to uncheck a checkbox

### ISSUE THREAD

**Issue by gudufoss** [jspresso/jspresso-ce#26]
Error message when you try to uncheck a checkbox on table view

StackTrace :
java.lang.IllegalArgumentException: Cannot invoke com.sun.proxy.$Proxy377.setCheckApplicant on bean class 'class com.sun.proxy.$Proxy377' - null - had objects of type "<null>" but expected signature "boolean"
       at org.apache.commons.beanutils.PropertyUtilsBean.invokeMethod(PropertyUtilsBean.java:2181)
       at org.apache.commons.beanutils.PropertyUtilsBean.setSimpleProperty(PropertyUtilsBean.java:2097)
       at org.apache.commons.beanutils.PropertyUtilsBean.setNestedProperty(PropertyUtilsBean.java:1903)
       at org.apache.commons.beanutils.PropertyUtilsBean.setProperty(PropertyUtilsBean.java:2010)
       at org.jspresso.framework.util.accessor.AbstractPropertyAccessor.setValue(AbstractPropertyAccessor.java:135)
       at org.jspresso.framework.binding.model.ModelPropertyConnector.setConnecteeValue(ModelPropertyConnector.java:299)
       at org.jspresso.framework.binding.AbstractValueConnector.setConnectorValue(AbstractValueConnector.java:493)
       at org.jspresso.framework.binding.AbstractValueConnector.valueChange(AbstractValueConnector.java:656)
       at org.jspresso.framework.util.event.ValueChangeSupport.fireValueChange(ValueChangeSupport.java:113)
       at org.jspresso.framework.binding.AbstractValueConnector.fireValueChange(AbstractValueConnector.java:757)
       at org.jspresso.framework.binding.AbstractValueConnector.fireConnectorValueChange(AbstractValueConnector.java:724)
       at org.jspresso.framework.binding.AbstractValueConnector.setConnectorValue(AbstractValueConnector.java:494)
       at org.jspresso.framework.binding.remote.RemoteValueConnector.setValueFromState(RemoteValueConnector.java:224)
       at org.jspresso.framework.application.frontend.controller.remote.AbstractRemoteController.handleCommand(AbstractRemoteController.java:380)
       at org.jspresso.framework.application.frontend.controller.remote.AbstractRemoteController.handleCommands(AbstractRemoteController.java:202)
       at org.jspresso.framework.application.startup.remote.RemoteStartup.handleCommands(RemoteStartup.java:88)
       at sun.reflect.GeneratedMethodAccessor399.invoke(Unknown Source)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
       at java.lang.reflect.Method.invoke(Unknown Source)
       at net.sf.qooxdoo.rpc.RemoteCallUtils.callCompatibleMethod(RemoteCallUtils.java:469)
       at net.sf.qooxdoo.rpc.RpcServlet.handleRPC(RpcServlet.java:374)
       at net.sf.qooxdoo.rpc.RpcServlet.doPost(RpcServlet.java:481)
       at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
       at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
       at org.jspresso.framework.util.http.HttpRequestHolder.doFilter(HttpRequestHolder.java:99)
       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
       at org.jboss.web.tomcat.filters.ReplyHeaderFilter.doFilter(ReplyHeaderFilter.java:96)
       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
       at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:235)
       at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
       at org.jboss.web.tomcat.security.SecurityAssociationValve.invoke(SecurityAssociationValve.java:190)
       at org.jboss.web.tomcat.security.JaccContextValve.invoke(JaccContextValve.java:92)
       at org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.process(SecurityContextEstablishmentValve.java:126)
       at org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.invoke(SecurityContextEstablishmentValve.java:70)
       at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
       at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
       at org.jboss.web.tomcat.service.jca.CachedConnectionValve.invoke(CachedConnectionValve.java:158)
       at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
       at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:330)
       at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:829)
       at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:598)
       at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:447)
       at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
       at java.lang.reflect.Method.invoke(Unknown Source)
       at org.apache.commons.beanutils.PropertyUtilsBean.invokeMethod(PropertyUtilsBean.java:2116)
       ... 46 more
 
<image002.jpg>

**Comment by vvandens** [comment]
`4.1.3-SNAPSHOT` is deployed with the fix
