### ISSUE TITLE
Filter per collections does not work (sometimes)

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#358]
This filter view makes the app crashing when launching LOV action on "postCodeZone" :

```
border('FlowSet.unit.filter.view') {
    center {
        form(columnCount:3) {
            fields {
                propertyView name: 'flows.depAddress.country', i18nNameKey: 'country'
                propertyView name: 'flows.depAddress.postcodeZone', i18nNameKey: 'postcodeZone'
                propertyView name: 'flows.depAddress', i18nNameKey: 'flows.depAddress'

                propertyView name: 'flows.arrAddress.country', i18nNameKey: 'country'
                propertyView name: 'flows.arrAddress.postcodeZone', i18nNameKey: 'postcodeZone'
                propertyView name: 'flows.arrAddress', i18nNameKey: 'flows.arrAddress'
            }
        }
    }
}
```

Both "country" and "postcodeZone" are references... but it works for country ??

Here is the stack trace :

```
17:22:58,549 ERROR [org.jspresso.framework.application.frontend.controller.AbstractFrontendController] [] An unexpected error occurred for user e242484 on session 4a2d56d8.
org.jspresso.framework.util.bean.MissingPropertyException: Missing property depAddress for bean class interface java.util.Set
	at org.jspresso.framework.util.bean.PropertyHelper.getPropertyDescriptor(PropertyHelper.java:61)
	at org.jspresso.framework.util.accessor.bean.BeanPropertyAccessor.<init>(BeanPropertyAccessor.java:56)
	at org.jspresso.framework.util.accessor.bean.BeanAccessorFactory.createPropertyAccessor(BeanAccessorFactory.java:58)
	at org.jspresso.framework.util.accessor.basic.BasicAccessorFactory.createPropertyAccessor(BasicAccessorFactory.java:54)
	at org.jspresso.framework.model.component.basic.AbstractComponentFactory.extractInitValue(AbstractComponentFactory.java:256)
	at org.jspresso.framework.application.backend.entity.ControllerAwareProxyEntityFactory.extractInitValue(ControllerAwareProxyEntityFactory.java:160)
	at org.jspresso.framework.model.component.basic.AbstractComponentFactory.applyInitializationMapping(AbstractComponentFactory.java:158)
	at org.jspresso.framework.application.backend.action.CreateQueryComponentAction.completeQueryComponent(CreateQueryComponentAction.java:147)
	at org.jspresso.framework.application.backend.action.CreateQueryComponentAction.execute(CreateQueryComponentAction.java:107)
	at org.jspresso.framework.application.backend.AbstractBackendController.executeBackend(AbstractBackendController.java:440)
	at org.jspresso.framework.application.backend.AbstractBackendController.execute(AbstractBackendController.java:422)
	at org.jspresso.framework.application.frontend.controller.AbstractFrontendController.executeBackend(AbstractFrontendController.java:1598)
	at org.jspresso.framework.application.frontend.controller.AbstractFrontendController.execute(AbstractFrontendController.java:593)
	at org.jspresso.framework.application.frontend.action.lov.LovAction.execute(LovAction.java:216)
	at org.jspresso.framework.application.frontend.controller.AbstractFrontendController.executeFrontend(AbstractFrontendController.java:1611)
	at org.jspresso.framework.application.frontend.controller.AbstractFrontendController.execute(AbstractFrontendController.java:600)
	at org.jspresso.framework.view.remote.RemoteActionFactory$ActionAdapter.actionPerformed(RemoteActionFactory.java:350)
	at org.jspresso.framework.application.frontend.controller.remote.AbstractRemoteController.handleCommand(AbstractRemoteController.java:474)

```

**Comment by vvandens** [comment]
The problem arises when using an initialization mapping
