### ISSUE TITLE
Crash when using Tmar export

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#396]
Crash when Tmar+ export from HRSample EE employees module :

```
21:12:08,988 ERROR [org.jspresso.framework.application.frontend.controller.AbstractFrontendController] [] An unexpected error occurred for user demo on session 1d1e5bc2.
org.jspresso.framework.model.component.ComponentException: Can not read component property contact.address on org.jspresso.hrsample.model.Employee$State
	at org.jspresso.hrsample.model.Employee$State.get(Employee.java:105)
	at org.jspresso.framework.model.entity.basic.BasicEntityInvocationHandler.retrievePropertyValue(BasicEntityInvocationHandler.java:178)
	at org.jspresso.framework.model.component.basic.AbstractComponentInvocationHandler.straightGetProperty(AbstractComponentInvocationHandler.java:1186)
	at org.jspresso.framework.application.backend.entity.ControllerAwareEntityInvocationHandler.straightGetProperty(ControllerAwareEntityInvocationHandler.java:282)
	at org.jspresso.framework.model.component.basic.AbstractComponentInvocationHandler.invoke(AbstractComponentInvocationHandler.java:239)
	at org.jspresso.framework.model.entity.basic.BasicEntityInvocationHandler.invoke(BasicEntityInvocationHandler.java:102)
	at com.sun.proxy.$Proxy21.straightGetProperty(Unknown Source)
	at org.jspresso.framework.application.backend.persistence.hibernate.HibernateBackendController.initializePropertyIfNeeded(HibernateBackendController.java:247)
	at org.jspresso.contrib.frontend.tmar.TmarCopyAllRecursivelyFrontAction.export(TmarCopyAllRecursivelyFrontAction.java:281)
	at org.jspresso.contrib.frontend.tmar.TmarCopyAllRecursivelyFrontAction$2.execute(TmarCopyAllRecursivelyFrontAction.java:226)
	at org.jspresso.framework.application.frontend.controller.AbstractFrontendController.executeFrontend(AbstractFrontendController.java:1611)
	at org.jspresso.framework.application.frontend.controller.AbstractFrontendController.execute(AbstractFrontendController.java:600)
	at org.jspresso.framework.application.action.AbstractAction.execute(AbstractAction.java:115)
	at org.jspresso.framework.application.frontend.controller.remote.AbstractRemoteController$1.execute(AbstractRemoteController.java:918)
	at org.jspresso.framework.application.frontend.controller.AbstractFrontendController.executeFrontend(AbstractFrontendController.java:1611)
	at org.jspresso.framework.application.frontend.controller.AbstractFrontendController.execute(AbstractFrontendController.java:600)
	at org.jspresso.framework.view.remote.RemoteActionFactory$ActionAdapter.actionPerformed(RemoteActionFactory.java:350)
	at org.jspresso.framework.application.frontend.controller.remote.AbstractRemoteController.handleCommand(AbstractRemoteController.java:473)
	at org.jspresso.framework.application.frontend.controller.remote.AbstractRemoteController.handleCommands(AbstractRemoteController.java:206)
	at org.jspresso.framework.application.startup.remote.RemoteStartup.handleCommands(RemoteStartup.java:89)
	at sun.reflect.GeneratedMethodAccessor334.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sf.qooxdoo.rpc.RemoteCallUtils.callCompatibleMethod(RemoteCallUtils.java:469)
	at net.sf.qooxdoo.rpc.RpcServlet.handleRPC(RpcServlet.java:374)
	at net.sf.qooxdoo.rpc.RpcServlet.doPost(RpcServlet.java:481)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:641)

```

**Comment by maximehamm** [comment]
Fixed from Tmar+
