### ISSUE TITLE
Table 'selectionModel' crashes for table having a computed descriptor as model 

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#451]
It crashes while selecting the first row :

Here is the code :

```
Component('CFilterFlowRound',
        extension: 'CFilterFlowRoundExtension',
        processor: 'CFilterFlowRoundProcessor') {
   ...
    // computed
    set 'filteredQuotationSets', ref:'QuotationSet', computed: true, cacheable: true
    set 'synchronizedFilteredQuotationSetsSelection', ref:'QuotationSet', computed: true, delegateWritable: true, id: 'CFilterFlowRound-synchronizeFilteredQuotationSetsSelection'
}

table(model: 'TenderRound-filter.CFilterFlowRound-filteredQuotationSets', readOnly: true,
                selectionModel: 'CFilterFlowRound-synchronizeFilteredQuotationSetsSelection',
                itemSelectionAction: 'synchronizeTenderConsolidationSelectionFrontAction') {
        columns {
                propertyView name: 'name'
                propertyView name: 'info'
                ....
         }
}
```
And the stack trace :

```
14:44:10,516 ERROR [org.jspresso.framework.application.frontend.controller.AbstractFrontendController] [] An unexpected error occurred for user e242484 on session 70f79971.
org.jspresso.framework.binding.ConnectorBindingException: java.lang.NoSuchMethodException: Property 'quotationsFilteredPerTenderRoundFilter' has no setter method in class 'class fr.gefco.metis.model.QuotationSet_$$_jvstdd3_46'
	at org.jspresso.framework.binding.model.ModelPropertyConnector.setConnecteeValue(ModelPropertyConnector.java:304)
	at org.jspresso.framework.binding.AbstractValueConnector.setConnectorValue(AbstractValueConnector.java:507)
	at org.jspresso.framework.binding.AbstractValueConnector.valueChange(AbstractValueConnector.java:681)
	at org.jspresso.framework.binding.AbstractCollectionConnector.valueChange(AbstractCollectionConnector.java:310)
	at org.jspresso.framework.binding.AbstractValueConnector.setModelConnector(AbstractValueConnector.java:574)
	at org.jspresso.framework.binding.DefaultMvcBinder.bind(DefaultMvcBinder.java:41)
	at org.jspresso.framework.binding.DefaultMvcBinder.bindChildren(DefaultMvcBinder.java:68)
	at org.jspresso.framework.binding.DefaultMvcBinder.bind(DefaultMvcBinder.java:44)
	at org.jspresso.framework.binding.DefaultMvcBinder.bindChildren(DefaultMvcBinder.java:68)
	at org.jspresso.framework.binding.DefaultMvcBinder.bind(DefaultMvcBinder.java:44)
	at org.jspresso.framework.binding.masterdetail.DefaultModelCascadingBinder$BoundConnectorSelectionListener.selectedItemChange(DefaultModelCascadingBinder.java:93)
	at org.jspresso.framework.util.event.ItemSelectionSupport.fireSelectedConnectorChange(ItemSelectionSupport.java:62)
	at org.jspresso.framework.binding.AbstractCompositeValueConnector.implFireSelectedItemChange(AbstractCompositeValueConnector.java:386)
	at org.jspresso.framework.binding.AbstractCompositeValueConnector.implFireSelectedConnectorChange(AbstractCompositeValueConnector.java:373)
	at org.jspresso.framework.binding.AbstractCollectionConnector.setSelectedIndices(AbstractCollectionConnector.java:279)
	at org.jspresso.framework.application.frontend.controller.remote.AbstractRemoteController.handleCommand(AbstractRemoteController.java:455)
	at org.jspresso.framework.application.frontend.controller.remote.AbstractRemoteController.handleCommands(AbstractRemoteController.java:206)
	at org.jspresso.framework.application.startup.remote.RemoteStartup.handleCommands(RemoteStartup.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sf.qooxdoo.rpc.RemoteCallUtils.callCompatibleMethod(RemoteCallUtils.java:469)

```

**Comment by vvandens** [comment]
I don't see any `quotationsFilteredPerTenderRoundFilter` in your SJS code...

**Comment by maximehamm** [comment]
I can't reproduce it anymore... forgot it. Sorry
