### ISSUE TITLE
Mobile UI is crashing when using a i18n key which starts with some model's field

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#536]
NB : 
- 'workflow' is a property of 'ThirdPartyRequest' entity
- 'workflow.informations' is an i18n key

Here is the SJS view :
```
 mobileForm (model:'ThirdPartyRequest', borderType: 'TITLED', name: 'workflow.informations', labelsPosition: 'NONE') {
            fields {
                propertyView name: 'workflowNextEventsAsHtml'
            }
        }

```
Here is the stack trace :
```
java.lang.NullPointerException
	at org.jspresso.framework.model.descriptor.basic.AbstractComponentDescriptor.getPropertyDescriptor(AbstractComponentDescriptor.java:372)
	at org.jspresso.framework.view.AbstractViewFactory.computeDynamicLabelPropertyName(AbstractViewFactory.java:1452)
	at org.jspresso.framework.view.remote.AbstractRemoteViewFactory.completeViewWithDynamicLabel(AbstractRemoteViewFactory.java:2055)
	at org.jspresso.framework.view.remote.AbstractRemoteViewFactory.completeViewWithDynamicLabel(AbstractRemoteViewFactory.java:1)
	at org.jspresso.framework.view.AbstractViewFactory.createView(AbstractViewFactory.java:370)
	at org.jspresso.framework.view.remote.mobile.MobileRemoteViewFactory.createView(MobileRemoteViewFactory.java:144)
	at org.jspresso.framework.view.remote.mobile.MobileRemoteViewFactory.createMobileCompositePageView(MobileRemoteViewFactory.java:407)
	at org.jspresso.framework.view.remote.mobile.MobileRemoteViewFactory.createCompositeView(MobileRemoteViewFactory.java:174)
	at org.jspresso.framework.view.AbstractViewFactory.createView(AbstractViewFactory.java:286)
	at org.jspresso.framework.view.remote.mobile.MobileRemoteViewFactory.createView(MobileRemoteViewFactory.java:144)
	at org.jspresso.framework.view.remote.mobile.MobileRemoteViewFactory.createMobileNavPageView(MobileRemoteViewFactory.java:320)
	at org.jspresso.framework.view.remote.mobile.MobileRemoteViewFactory.createCompositeView(MobileRemoteViewFactory.java:177)
	at org.jspresso.framework.view.AbstractViewFactory.createView(AbstractViewFactory.java:286)
	at org.jspresso.framework.view.remote.mobile.MobileRemoteViewFactory.createView(MobileRemoteViewFactory.java:144)
	at org.jspresso.
```

**Comment by maximehamm** [comment]
NB : The property here is :

`    any 'workflow', class: 'org.jspresso.contrib.fjs.core.JspressoWorkFlow', computed: true, delegateWritable: true`
