### ISSUE TITLE
Crash when clicking on pivot's module cell

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#644]
When clicking into pivot's cell :

18:53:31,049 ERROR [org.jspresso.framework.application.frontend.controller.AbstractFrontendController] [] An unexpected error occurred for user e242484 on session b3839c5.
java.lang.NullPointerException
	at org.jspresso.framework.gui.remote.RTabContainer.translateExcludingHiddenChildren(RTabContainer.java:174)
	at org.jspresso.framework.view.remote.DefaultRemoteViewFactory.selectChildViewIndex(DefaultRemoteViewFactory.java:429)
	at org.jspresso.framework.view.remote.DefaultRemoteViewFactory.selectChildViewIndex(DefaultRemoteViewFactory.java:1)
	at org.jspresso.framework.view.AbstractViewFactory$3.setCurrentViewIndex(AbstractViewFactory.java:961)
	at org.jspresso.framework.ext.pivot.frontend.action.PivotCellSelectionToModuleListFrontAction.execute(PivotCellSelectionToModuleListFrontAction.java:98)
	at org.jspresso.framework.application.frontend.controller.AbstractFrontendController.executeFrontend(AbstractFrontendController.java:1647)
	at org.jspresso.framework.application.frontend.controller.AbstractFrontendController.execute(AbstractFrontendController.java:606)
	at org.jspresso.framework.view.remote.RemoteActionFactory$ActionAdapter.actionPerformed(RemoteActionFactory.java:359)
	at org.jspresso.framework.application.frontend.controller.remote.AbstractRemoteController.handleCommand(AbstractRemoteController.java:484)
	at org.jspresso.framework.application.frontend.controller.remote.AbstractRemoteController.handleCommands(AbstractRemoteController.java:209)
	at org.jspresso.framework.application.startup.remote.RemoteStartup.handleCommands(RemoteStartup.java:89)
	at sun.reflect.GeneratedMethodAccessor341.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sf.qooxdoo.rpc.RemoteCallUtils.callCompatibleMethod(RemoteCallUtils.java:469)
	at net.sf.qooxdoo.rpc.RpcServlet.handleRPC(RpcServlet.java:374)
	at net.sf.qooxdoo.rpc.RpcServlet.doPost(RpcServlet.java:481)

**Comment by maximehamm** [comment]
GIT : https://github.com/jspresso/jspresso-ce/issues/644
