### ISSUE TITLE
Dynamic border title is crashing : Property [title] does not exist

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#658]
The stack trace is :
```
21:30:13,350 ERROR [org.jspresso.framework.application.frontend.controller.AbstractFrontendController] [] An unexpected error occurred for user e242484 on session 2bad484e.
org.jspresso.framework.binding.ConnectorBindingException: Property [title] does not exist on {fr.gefco.metis.model.TenderRound}.
	at org.jspresso.framework.binding.model.ModelRefPropertyConnector.getChildConnector(ModelRefPropertyConnector.java:180)
	at org.jspresso.framework.binding.DefaultMvcBinder.bindChildren(DefaultMvcBinder.java:64)
	at org.jspresso.framework.binding.DefaultMvcBinder.bind(DefaultMvcBinder.java:44)
	at org.jspresso.framework.binding.DefaultMvcBinder.bindChildren(DefaultMvcBinder.java:68)
	at org.jspresso.framework.binding.DefaultMvcBinder.bind(DefaultMvcBinder.java:44)
	at org.jspresso.framework.binding.DefaultMvcBinder.bindChildren(DefaultMvcBinder.java:68)
	at org.jspresso.framework.binding.DefaultMvcBinder.bind(DefaultMvcBinder.java:44)
	at org.jspresso.framework.view.AbstractViewFactory.refreshCardView(AbstractViewFactory.java:1172)
```

The code is :
```
border('TenderRound.quotationSet.submodule.view') {
    north {
        border(parent: 'Tender.header.common.view', model: 'TenderRound-flowSet', borderType: 'TITLED_ACTIONS', name: 'title') {
            actionMap {
                actionList(renderingOptions: 'LABEL_ICON', collapsable: true) {
                    action parent: 'saveModuleObjectFrontAction'
                    action ref: 'reloadModuleObjectFrontAction'
                }
                actionList ('DOC') {
                    action ref: 'displayModuleDocumentationAction'
                    action parent: 'displayModuleDocumentationNoneAction', grantedRoles: ['Adm', 'Root']
                }
            }
        }
    }
```

Here is a workaround :
```
border('TenderRound.quotationSet.submodule.view') {
    north {
        border(model: 'TenderRound-flowSet') {
            center {
                border(parent: 'Tender.header.common.view', borderType: 'TITLED_ACTIONS', name: 'title') {
                    actionMap {
                        actionList(renderingOptions: 'LABEL_ICON', collapsable: true) {
                            action parent: 'saveModuleObjectFrontAction'
                            action ref: 'reloadModuleObjectFrontAction'
                        }
                        actionList('DOC') {
                            action ref: 'displayModuleDocumentationAction'
                            action parent: 'displayModuleDocumentationNoneAction', grantedRoles: ['Adm', 'Root']
                        }
                    }
                }
            }
        }
    }
```

**Comment by maximehamm** [comment]
NB : I think this is a regression in 5.7.2-SNAPSHOT
