### ISSUE TITLE
Repeater with card view inside is crashing

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#666]
Here is the stack trace : 
```
org.jspresso.framework.binding.MissingConnectorException: Missing model connector for key operations
	at org.jspresso.framework.binding.DefaultMvcBinder.bindChildren(DefaultMvcBinder.java:66)
	at org.jspresso.framework.binding.DefaultMvcBinder.bind(DefaultMvcBinder.java:44)
	at org.jspresso.framework.view.AbstractViewFactory.refreshCardView(AbstractViewFactory.java:1172)
	at org.jspresso.framework.view.AbstractViewFactory$6.valueChange(AbstractViewFactory.java:1106)
	at org.jspresso.framework.util.event.ValueChangeSupport.fireValueChange(ValueChangeSupport.java:113)
	at org.jspresso.framework.binding.AbstractValueConnector.fireValueChange(AbstractValueConnector.java:781)
```

Here is the SJS view : 
```
border('FlowSet.operations.view', name: 'flowsOperationTitle') {
    center {
        repeater(model: 'FlowSet-operationsPerType') { //, styleName: 'compactrepeater') {
            repeat {
                propertyCardView(model: 'CFlowSetOperationKind', property: 'kind') {
                    views {

                        // PKP
                        border('PKP', model: 'CFlowSetOperationKind', borderType: 'TITLED', i18nNameKey: 'EOperationKind.PKP') {
                            center {
                                table(model: 'CFlowSetOperationKind-operations', permId: '@a340-47d7-9381-abe09') {
                                    columns {

                                        //TODO Subsidiary
                                        propertyView name: 'depPlatform', paramSets: ['style.flow.background'], readOnly: true
                                        propertyView name: 'distance', paramSets: ['style.flow.background'], readOnly: true
                                        propertyView name: 'costType', paramSets: ['style.load.background']
                                        propertyView name: 'value', paramSets: ['style.load.background']
                                        propertyView name: 'valueDivisor', paramSets: ['style.load.background']
                                        propertyView name: 'truckHeight', paramSets: ['style.load.background']
                                    }
                                }
                            }
                        }

                        // CXD, CXE
                        border('CXD', model: 'CFlowSetOperationKind', borderType: 'TITLED', i18nNameKey: 'EOperationKind.CXD') {
                            center {
                                table(model: 'CFlowSetOperationKind-operations', permId: '@5402-43fe-8209-d1b12') {
                                    columns {

                                        //TODO Subsidiary
                                        propertyView name: 'depPlatform', paramSets: ['style.flow.background'], readOnly: true
                                        propertyView name: 'costType', paramSets: ['style.load.background']
                                        propertyView name: 'value', paramSets: ['style.load.background']
                                    }
                                }
                            }
                        }

                        // TRK, TRE
                        border('TRK', model: 'CFlowSetOperationKind', borderType: 'TITLED', i18nNameKey: 'EOperationKind.TRK') {
                            center {
                                table(model: 'CFlowSetOperationKind-operations', permId: '@a0a0-4242-884c-d5076') {
                                    columns {

                                        //TODO Subsidiary
                                        propertyView name: 'depPlatform', paramSets: ['style.flow.background'], readOnly: true
                                        propertyView name: 'arrPlatform', paramSets: ['style.flow.background'], readOnly: true
                                        propertyView name: 'distance', paramSets: ['style.flow.background'], readOnly: true
                                        propertyView name: 'costType', paramSets: ['style.load.background']
                                        propertyView name: 'value', paramSets: ['style.load.background']
                                        propertyView name: 'valueDivisor', paramSets: ['style.load.background']
                                        propertyView name: 'truckHeight', paramSets: ['style.load.background']
                                    }
                                }
                            }
                        }

                        // DEL
                        border('DEL', model: 'CFlowSetOperationKind', borderType: 'TITLED', i18nNameKey: 'EOperationKind.DEL') {
                            center {
                                table(model: 'CFlowSetOperationKind-operations', permId: '@3575-43bc-bae0-a060f') {
                                    columns {

                                        //TODO Subsidiary
                                        propertyView name: 'arrPlatform', paramSets: ['style.flow.background'], readOnly: true
                                        propertyView name: 'distance', paramSets: ['style.flow.background'], readOnly: true
                                        propertyView name: 'costType', paramSets: ['style.load.background']
                                        propertyView name: 'value', paramSets: ['style.load.background']
                                        propertyView name: 'valueDivisor', paramSets: ['style.load.background']
                                        propertyView name: 'truckHeight', paramSets: ['style.load.background']
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

Here is the relate SJS model : 
```
Entity('FlowSet') {
   ...
    set 'operationsPerType', ref: 'CFlowSetOperationKind', computed: true
}
Component('CFlowSetOperationKind') {
    string 'kind'
    set 'operations', ref: 'FlowSetOperation'
}
Entity('FlowSetOperation') {
   ...
}
```

The model connecter's has no child named PKP ??
![image](https://user-images.githubusercontent.com/4968224/55538667-42bdfb80-56bf-11e9-8c05-d66c72dfbc05.png)

![image](https://user-images.githubusercontent.com/4968224/55538657-3b96ed80-56bf-11e9-8788-7404950debe2.png)

**Comment by maximehamm** [comment]
NB : Trying with an old-school "basicCardView" : 

```
border('FlowSet.operations.view', name: 'flowsOperationTitle') {
    center {
        repeater(model: 'FlowSet-operationsPerType') { //, styleName: 'compactrepeater') {
            repeat {

                border(model: 'CFlowSetOperationKind') {
                    center {
                        basicCardView(model: 'CFlowSetOperationKind', selector: 'CFlowSetOperationKind.selector',
                                views: ['PKP': 'CFlowSetOperationKind.PKP.view'])
                    }
                }
```

New exception is :
```
java.lang.NullPointerException
	at org.jspresso.framework.binding.DefaultMvcBinder.bind(DefaultMvcBinder.java:38)
	at org.jspresso.framework.binding.DefaultMvcBinder.bind(DefaultMvcBinder.java:47)
	at org.jspresso.framework.view.AbstractViewFactory.refreshCardView(AbstractViewFactory.java:1172)
	at org.jspresso.framework.view.AbstractViewFactory$6.valueChange(AbstractViewFactory.java:1106)
	at org.jspresso.framework.util.event.ValueChangeSupport.fireValueChange(ValueChangeSupport.java:113)

```
